### ISSUE TITLE
Jupyter Lab JDAViz/Specviz Compatibility

### ISSUE THREAD

**Issue by nkerman** [spacetelescope/jdaviz#327]
There seems to be a lack of documentation on running `JDAViz` and `specviz` from within a Jupyter Lab environment. 
- With the basic installation of jupyter lab, the widget fails to load after:
```python
from jdaviz import SpecViz
specviz = SpecViz()
specviz.app
```

- After installing the jupyter lab extensions suggested by [glue-jupyter here](https://glue-jupyter.readthedocs.io/en/latest/installing.html#jupyter-lab), a strangely formatted widget does appear (see attached screenshot).
<img width="1346" alt="Screen Shot 2020-10-06 at 5 01 31 PM" src="https://user-images.githubusercontent.com/13221946/95259727-a154c000-07f5-11eb-97cd-b1179161d796.png">

**Comment by eteq** [comment]
Oh that's weird with the formatting ... Although I guess I'm a bit :clap:  that it worked at all!

I guess with that I take this issue as now two tasks

- [ ] We need to work out why the formatting is weird
- [ ] Update the jdaviz documentation to clearly state that if using jupyter lab you need to follow the jupyter lab extra install steps

(Longer term there's a scheme afoot to update jupyterlab to be more compatible with glue-jupyter, but I think that discussion belongs in the glue-jupyter repo rather than here.)

**Comment by maartenbreddels** [comment]
If jupyter lab 3.0 is released, we don't have to build the jupyter lab package anymore, and a pip install should be enough.

Issue related to non-federated bundles, which needs to be solved before ipyvolume can work:
 * https://github.com/jupyterlab/jupyterlab/issues/9289
 * (Can be ignored if ipydatawidgets and pythreejs become federated bundles)

These widget libraries are ready (and waiting for the final jupyter lab 3.0 releases)
 * bqplot: https://github.com/bqplot/bqplot/pull/1222
 * bqplot-image-gl: https://github.com/glue-viz/bqplot-image-gl/pull/35/
 * ipyvolume: https://github.com/maartenbreddels/ipyvolume/pull/355

**Comment by mariobuikhuizen** [comment]
Ipyvue and ipyvuetify work correctly in jupyter lab 3 as federated extensions (not as classic extensions).

In addition to the widget libraries @maartenbreddels posted, these libraries are ready:
* https://github.com/mariobuikhuizen/ipyvue/pull/19
* https://github.com/mariobuikhuizen/ipyvuetify/pull/110
* https://github.com/nmearl/ipysplitpanes/pull/7
* https://github.com/nmearl/ipygoldenlayout/pull/12

**Comment by maartenbreddels** [comment]
Relevant PR's:
 * https://github.com/jupyter-widgets/pythreejs/pull/342
 * https://github.com/vidartf/ipydatawidgets/pull/41

Outstanding issue:
 * https://github.com/bqplot/bqplot/issues/1245

**Comment by mariobuikhuizen** [comment]
One more PR we overlooked: https://github.com/matplotlib/ipympl/pull/272

**Comment by jasongrout** [comment]
FYI, see also https://github.com/jupyterlab/jupyterlab/issues/9461 for more compatibility information.

**Comment by maartenbreddels** [comment]
Thanks Jason.

bqplot-image-gl 1.1.0 is lab3 compatible (modulo a bqplot dependency not playing nice https://github.com/bqplot/bqplot/pull/1271 )

**Comment by maartenbreddels** [comment]
ipyvolume 0.6.0-alpha.8 is compatible with jupyter lab 3.0
```
pip install ipyvolume==0.6.0a8
```

The only two missing now are:
 * https://github.com/nmearl/ipygoldenlayout/pull/12 (needs a merge and release)
 * https://github.com/nmearl/ipysplitpanes/pull/7 (*is* merged, just needs a release)

**Comment by nmearl** [comment]
`ipygoldenlayout` (v0.4.0) has been updated and released, and `ipysplitpanes` (v0.2.0) has also been updated and released.

**Comment by maartenbreddels** [comment]
With all the latest widget packages, jdaviz renders in jupyter lab 3.0 without needing nodejs, there are some issue left:
 * https://github.com/glue-viz/bqplot-image-gl/pull/51  (fixed in bqpot-image-gl 1.3.2, just released)
 * https://github.com/bqplot/bqplot/pull/1340

If these are both released, jdaviz should be fully functional.

**Comment by ojustino** [comment]
I'm following up from this morning's scrum to report my own experience with Specviz in Jupyter Lab. There are no error messages and the top toolbar appears, but the viewer does not.

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/12895749/118166824-f728c080-b3f3-11eb-82ab-de43d9ff2e88.png">

I think things are still happening behind the scenes because I can run methods like `load_spectrum()` and `load_line_list()` without errors or warnings. Everything does work as intended when I'm in a classic notebook.

**Comment by pllim** [comment]
Has this been completely resolved by #625 or is there something else that needs fixing?
